apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-http-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: voting.azf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-voting-http-demo-http
            port: 
              number: 80